services:

  db:
    image: mysql:8.0
    container_name: ${DB_NAME}
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "${DB_PORT}:3306"

  php:
    container_name: ${APP_NAME}
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    platform: linux/amd64
    ports:
      - "${APP_PORT}:80"
    volumes:
      - ./src:/var/www/html
    environment:
      - PHP_IDE_CONFIG=serverName=Docker
    networks:
      - app-network
    depends_on:
      - db

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
    driver: local